
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Tue Apr 24 12:51:12 BST 2007
//----------------------------------------------------

package org.oXML.xpath.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PRECEDING_SIBLING = 39;
  public static final int LTE = 7;
  public static final int ASTERISK = 13;
  public static final int NAMESPACE = 36;
  public static final int EQUALS = 4;
  public static final int SLASH = 23;
  public static final int COMMENT = 41;
  public static final int SLASHSLASH = 24;
  public static final int LPAREN = 9;
  public static final int CHILD = 31;
  public static final int MINUS = 17;
  public static final int PROCESSING_INSTRUCTION = 43;
  public static final int BAR = 15;
  public static final int RPAREN = 10;
  public static final int AND = 21;
  public static final int LT = 5;
  public static final int OR = 20;
  public static final int COMMA = 2;
  public static final int FOLLOWING_SIBLING = 35;
  public static final int DOTDOT = 26;
  public static final int DIV = 18;
  public static final int NC_NAME = 46;
  public static final int DESCENDANT_OR_SELF = 33;
  public static final int PLUS = 16;
  public static final int DOT = 25;
  public static final int DESCENDANT = 32;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int SELF = 40;
  public static final int NUMBER = 47;
  public static final int MOD = 19;
  public static final int PRECEDING = 38;
  public static final int ANCESTOR_OR_SELF = 29;
  public static final int GTE = 8;
  public static final int ANCESTOR = 28;
  public static final int LITERAL = 45;
  public static final int COLON = 27;
  public static final int LANGLE = 11;
  public static final int NOTEQUALS = 3;
  public static final int DOLLAR = 22;
  public static final int RANGLE = 12;
  public static final int PARENT = 37;
  public static final int FOLLOWING = 34;
  public static final int TEXT = 42;
  public static final int AT = 14;
  public static final int ATTRIBUTE = 30;
  public static final int GT = 6;
  public static final int NODE = 44;
}

